apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: akamai-dashboard
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: akamai-dashboard
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: splunk-service
  namespace: akamai-dashboard
spec:
  selector:
    app: splunk
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
